apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mfrestorepvc
spec:
  storageClassName: mfrestorestorage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfsrestorestorage
spec:
  storageClassName: mfrestorestorage
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data/mf/prod_dumps/
    type: DirectoryOrCreate     

---

apiVersion: batch/v1
kind: Job
metadata:
  name: mfrestore
spec:
  template:
    spec:
      containers: 
      - name: mfrestore
        image: holgerfischer/myfinance:0.13.0-SNAPSHOT-mfdumprestore 
        volumeMounts:
         - name: myfinancerestore
           mountPath: /var/dumps           
        env:
        - name: FILENAME
          value: "backupOn2020-05-22-10-10.psql.gz"   
        - name: PASSWORD
          value: vulkan   
      restartPolicy: OnFailure  
      volumes:
      - name: myfinancerestore
        persistentVolumeClaim:
          claimName: mfrestorepvc     
  backoffLimit: 2   